services:
  azurestorageaccount:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7777:7777
      - 7778:7778
      - 7779:7779
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
